const params = new URLSearchParams(window.location.search);
const saved = JSON.parse(localStorage.getItem('shopmate-demo-data') || 'null');
const data = saved || { shop: { name: 'Maison Miro', description: 'Thoughtful objects for everyday rituals.', hours: 'Mon-Sat, 10:00-19:00' }, products: [{ name: 'Linen Table Runner', description: 'Natural flax, 180cm', price: 38, stock_quantity: 12, in_stock: true }] };
const cart = new Map();
const clean = value => String(value || '').replace(/[<>&]/g, '');
const catalog = document.querySelector('#catalog');
const money = value => `₹${Number(value || 0).toLocaleString('en-IN')}`;
document.title = `${data.shop.name} | Shop`;
document.querySelector('#shop-name').textContent = data.shop.name;
document.querySelector('#shop-hours').textContent = data.shop.hours || '';
document.querySelector('#shop-description').textContent = data.shop.description || 'Browse our latest collection.';
function render() { catalog.innerHTML = (data.products || []).map((product, index) => { const quantity = cart.get(product.id || index) || 0; const available = Number(product.stock_quantity ?? (product.in_stock === false ? 0 : 10)); return `<article class="product"><div class="product-art">${clean(product.name?.[0] || '✦')}</div><div class="product-body"><h2>${clean(product.name)}</h2><p>${clean(product.description || 'Made with care for your everyday life.')}</p><div class="product-meta"><span class="price">${money(product.price)}</span><span class="stock ${available ? '' : 'out'}">${available ? `${available} available` : 'Out of stock'}</span></div><div class="quantity"><button data-minus="${index}" aria-label="Remove one">−</button><span>${quantity}</span><button data-plus="${index}" aria-label="Add one" ${available ? '' : 'disabled'}>+</button></div></div></article>`; }).join('') || '<p>No products available yet.</p>'; catalog.querySelectorAll('[data-plus]').forEach(button => button.addEventListener('click', () => changeQuantity(Number(button.dataset.plus), 1))); catalog.querySelectorAll('[data-minus]').forEach(button => button.addEventListener('click', () => changeQuantity(Number(button.dataset.minus), -1))); updateCart(); }
function changeQuantity(index, change) { const product = data.products[index]; const key = product.id || index; const available = Number(product.stock_quantity ?? (product.in_stock === false ? 0 : 10)); const next = Math.max(0, Math.min(available, (cart.get(key) || 0) + change)); if (next) cart.set(key, next); else cart.delete(key); render(); }
function updateCart() { const items = [...cart.entries()].reduce((sum, [, quantity]) => sum + quantity, 0); const total = [...cart.entries()].reduce((sum, [key, quantity]) => { const product = data.products.find((item, index) => String(item.id || index) === String(key)); return sum + Number(product?.price || 0) * quantity; }, 0); document.querySelector('#cart-count').textContent = `${items} item${items === 1 ? '' : 's'}`; document.querySelector('#cart-total').textContent = money(total); document.querySelector('#checkout').disabled = !items; }
document.querySelector('#checkout').addEventListener('click', () => { if (cart.size) { document.querySelector('#order-summary').textContent = `${[...cart.entries()].map(([key, quantity]) => { const product = data.products.find((item, index) => String(item.id || index) === String(key)); return `${product.name} × ${quantity}`; }).join(', ')} · ${document.querySelector('#cart-total').textContent}`; document.querySelector('#order-modal').classList.add('open'); } });
document.querySelector('#close-modal').addEventListener('click', () => document.querySelector('#order-modal').classList.remove('open'));
document.querySelector('#order-form').addEventListener('submit', event => { event.preventDefault(); const customer = document.querySelector('#customer-name').value.trim(); const email = document.querySelector('#customer-email').value.trim(); const total = [...cart.entries()].reduce((sum, [key, quantity]) => { const product = data.products.find((item, index) => String(item.id || index) === String(key)); return sum + Number(product?.price || 0) * quantity * 1.18; }, 0); data.orders ||= []; data.orders.unshift({ id: `ORD-${String(data.orders.length + 1).padStart(4, '0')}`, customer, visitor_email: email, item: [...cart.entries()].map(([key, quantity]) => { const product = data.products.find((item, index) => String(item.id || index) === String(key)); return `${product.name} x${quantity}`; }).join(', '), total, status: 'Pending', date: new Date().toISOString() }); localStorage.setItem('shopmate-demo-data', JSON.stringify(data)); document.querySelector('#order-modal').classList.remove('open'); cart.clear(); render(); const toast = document.querySelector('#shop-toast'); toast.textContent = 'Order request sent. The shop will confirm it soon.'; toast.classList.add('show'); setTimeout(() => toast.classList.remove('show'), 3500); });
render();
