const params = new URLSearchParams(window.location.search);
const saved = JSON.parse(localStorage.getItem('shopmate-demo-data') || 'null');
const data = saved || { shop: { name: 'Maison Miro', description: 'Thoughtful objects for everyday rituals.', hours: 'Mon-Sat, 10:00-19:00' }, products: [{ name: 'Linen Table Runner', description: 'Natural flax, 180cm', price: 38, stock_quantity: 12, in_stock: true }] };
const cart = new Map();
const clean = value => String(value || '').replace(/[<>&]/g, '');
const catalog = document.querySelector('#catalog');
const money = value => `₹${Number(value || 0).toLocaleString('en-IN')}`;
document.head.insertAdjacentHTML('beforeend', '<link rel="stylesheet" href="order-status.css">');
document.title = `${data.shop.name} | Shop`;
document.querySelector('#shop-name').textContent = data.shop.name;
document.querySelector('#shop-hours').textContent = data.shop.hours || '';
document.querySelector('#shop-description').textContent = data.shop.description || 'Browse our latest collection.';
let activeOrderId = null;
function showOrderStatus(order) { activeOrderId = order.id; const panel = document.querySelector('#order-status'); panel.classList.add('show'); panel.classList.toggle('confirmed', order.status === 'Confirmed'); document.querySelector('#status-icon').textContent = order.status === 'Confirmed' ? '✓' : '…'; document.querySelector('#status-title').textContent = order.status === 'Confirmed' ? 'Order confirmed' : 'Order received'; document.querySelector('#status-copy').textContent = order.status === 'Confirmed' ? 'Great news. The shop has confirmed your order and will prepare it soon.' : 'Your request is with the shop. We will confirm availability shortly.'; document.querySelector('#status-number').textContent = `${order.id} · ${order.status}`; }
function checkOrderStatus() { if (!activeOrderId) return; const current = (JSON.parse(localStorage.getItem('shopmate-demo-data') || '{}').orders || []).find(order => order.id === activeOrderId); if (current) showOrderStatus(current); }
function render() { catalog.innerHTML = (data.products || []).map((product, index) => { const quantity = cart.get(product.id || index) || 0; const available = Number(product.stock_quantity ?? (product.in_stock === false ? 0 : 10)); return `<article class="product"><div class="product-art">${clean(product.name?.[0] || '✦')}</div><div class="product-body"><h2>${clean(product.name)}</h2><p>${clean(product.description || 'Made with care for your everyday life.')}</p><div class="product-meta"><span class="price">${money(product.price)}</span><span class="stock ${available ? '' : 'out'}">${available ? `${available} available` : 'Out of stock'}</span></div><div class="quantity"><button data-minus="${index}" aria-label="Remove one">−</button><span>${quantity}</span><button data-plus="${index}" aria-label="Add one" ${available ? '' : 'disabled'}>+</button></div></div></article>`; }).join('') || '<p>No products available yet.</p>'; catalog.querySelectorAll('[data-plus]').forEach(button => button.addEventListener('click', () => changeQuantity(Number(button.dataset.plus), 1))); catalog.querySelectorAll('[data-minus]').forEach(button => button.addEventListener('click', () => changeQuantity(Number(button.dataset.minus), -1))); updateCart(); }
function changeQuantity(index, change) { const product = data.products[index]; const key = product.id || index; const available = Number(product.stock_quantity ?? (product.in_stock === false ? 0 : 10)); const next = Math.max(0, Math.min(available, (cart.get(key) || 0) + change)); if (next) cart.set(key, next); else cart.delete(key); render(); }
function updateCart() { const items = [...cart.entries()].reduce((sum, [, quantity]) => sum + quantity, 0); const total = [...cart.entries()].reduce((sum, [key, quantity]) => { const product = data.products.find((item, index) => String(item.id || index) === String(key)); return sum + Number(product?.price || 0) * quantity; }, 0); document.querySelector('#cart-count').textContent = `${items} item${items === 1 ? '' : 's'}`; document.querySelector('#cart-total').textContent = money(total); document.querySelector('#checkout').disabled = !items; }
document.querySelector('#checkout').addEventListener('click', () => { if (cart.size) { document.querySelector('#order-summary').textContent = `${[...cart.entries()].map(([key, quantity]) => { const product = data.products.find((item, index) => String(item.id || index) === String(key)); return `${product.name} × ${quantity}`; }).join(', ')} · ${document.querySelector('#cart-total').textContent}`; document.querySelector('#order-modal').classList.add('open'); } });
document.querySelector('#close-modal').addEventListener('click', () => document.querySelector('#order-modal').classList.remove('open'));
document.querySelector('#order-form').addEventListener('submit', event => { event.preventDefault(); const customer = document.querySelector('#customer-name').value.trim(); const email = document.querySelector('#customer-email').value.trim(); const total = [...cart.entries()].reduce((sum, [key, quantity]) => { const product = data.products.find((item, index) => String(item.id || index) === String(key)); return sum + Number(product?.price || 0) * quantity * 1.18; }, 0); data.orders ||= []; const order = { id: `ORD-${String(data.orders.length + 1).padStart(4, '0')}`, source: 'public-shop', customer, visitor_email: email, item: [...cart.entries()].map(([key, quantity]) => { const product = data.products.find((item, index) => String(item.id || index) === String(key)); return `${product.name} x${quantity}`; }).join(', '), total, status: 'Pending', date: new Date().toISOString() }; data.orders.unshift(order); localStorage.setItem('shopmate-demo-data', JSON.stringify(data)); showOrderStatus(order); if ('BroadcastChannel' in window) new BroadcastChannel('shopmate-orders').postMessage({ type: 'order-created', order }); document.querySelector('#order-modal').classList.remove('open'); cart.clear(); render(); const toast = document.querySelector('#shop-toast'); toast.textContent = 'Order request sent. The shop will confirm it soon.'; toast.classList.add('show'); setTimeout(() => toast.classList.remove('show'), 3500); });
window.addEventListener('storage', checkOrderStatus);
if ('BroadcastChannel' in window) { const orderChannel = new BroadcastChannel('shopmate-orders'); orderChannel.onmessage = event => { if (event.data?.type === 'order-updated' && event.data.order.id === activeOrderId) showOrderStatus(event.data.order); }; }
render();
